"""initial schema

Revision ID: 972630a97a5f
Revises: 
Create Date: 2026-08-23 20:01:52.613488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972630a97a5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('format', sa.Enum('PDF', 'DOC', 'DOCX', 'PPTX', 'TXT', 'WEB', name='docformat', native_enum=False, length=8), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('upload', 'url', name='docsource', native_enum=False, length=8), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'extracting', 'understanding', 'preparing', 'ready', 'failed', name='docstatus', native_enum=False, length=16), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('words', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('ocr_method', sa.String(length=64), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('default_length', sa.Enum('Short', 'Medium', 'Long', name='summarylength', native_enum=False, length=16), nullable=False),
    sa.Column('default_style', sa.Enum('executive', 'key_points', 'detailed', 'study_notes', 'action_items', name='summarystyle', native_enum=False, length=24), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('tts_voice', sa.String(length=64), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('extracted_texts',
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('summary_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.Enum('extract', 'summarize', name='jobtype', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=16), nullable=False),
    sa.Column('stage', sa.Enum('uploaded', 'extracting', 'understanding', 'preparing', name='jobstage', native_enum=False, length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('total_stages', sa.Integer(), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_document_id'), 'jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_jobs_summary_id'), 'jobs', ['summary_id'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=False),
    sa.Column('format', sa.Enum('PDF', 'DOC', 'DOCX', 'PPTX', 'TXT', 'WEB', name='docformat', native_enum=False, length=8), nullable=False),
    sa.Column('excerpt', sa.String(length=2048), nullable=False),
    sa.Column('length', sa.Enum('Short', 'Medium', 'Long', name='summarylength', native_enum=False, length=16), nullable=False),
    sa.Column('style', sa.Enum('executive', 'key_points', 'detailed', 'study_notes', 'action_items', name='summarystyle', native_enum=False, length=24), nullable=False),
    sa.Column('category', sa.Enum('Research', 'Finance', 'Tech', 'Internal', name='category', native_enum=False, length=16), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('words', sa.Integer(), nullable=True),
    sa.Column('tldr', sa.String(length=4096), nullable=False),
    sa.Column('takeaways', sa.JSON(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('highlight', sa.String(length=2048), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ready', 'generating', 'failed', name='summarystatus', native_enum=False, length=16), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_document_id'), 'summaries', ['document_id'], unique=False)
    op.create_index(op.f('ix_summaries_user_id'), 'summaries', ['user_id'], unique=False)
    op.create_table('share_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('summary_id', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_share_tokens_summary_id'), 'share_tokens', ['summary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_tokens_summary_id'), table_name='share_tokens')
    op.drop_table('share_tokens')
    op.drop_index(op.f('ix_summaries_user_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_document_id'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_summary_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_document_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('extracted_texts')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
